### ISSUE TITLE
q values for combos of format and profile

### ISSUE THREAD

**Issue by ericprud** [ProfileNegotiation/I-D-Profile-Negotiation#22]
You may want to tie q values to combos of format and profile. You could do that in a media type header like `Accept`:
```
Accept:
    text/format-1;profile="profile-A";q=1.0,
    text/format-2;profile="profile-A";q=0.9,
    text/format-2;profile="profile-B";q=0.8,
    text/format-1;profile="profile-B";q=0.7
```
I originally thought FHIR had a use case but now believe that `Accept-Profile:` is more appropriate 'cause the profile q values are orthogonal to the format  values.

**Comment by RubenVerborgh** [comment]
We decided to currently keep the dimensions orthogonal, as we do not want the spec to go too deeply into such negotiations.
