### ISSUE TITLE
[Use case] JSON-LD framing

### ISSUE THREAD

**Issue by ericprud** [ProfileNegotiation/I-D-Profile-Negotiation#27]
[JSON-LD: specify the json-ld profile](json-ld/json-ld.org#491) implies a need for separate specification of a document form (e.g. [json-ld:compacted](https://www.w3.org/TR/json-ld/#compacted-document-form)) and the framing. This could be handled analogously to the pairs used to represent XML namespace and schemaLocations. Gregg drafted [an example](https://github.com/json-ld/json-ld.org/issues/491#issuecomment-345459424):
```
Accept-Profile: <http://www.w3.org/ns/json-ld#compacted https://example.com/context.jsonld>
```
Related: #21

**Comment by RubenVerborgh** [comment]
We currently don't have a mechanism for stating combined profile preferences, and do not have one in mind for this first draft. This might be a later extension.

Currently, they could be stated as independent preferences (that the server will try to satisfy), or @larsgsvensson's suggestion above can be followed.
