### ISSUE TITLE
Figure 4 status code mismatch 

### ISSUE THREAD

**Issue by YoucTagh** [ProfileNegotiation/I-D-Profile-Negotiation#33]
In [Figure 4](https://datatracker.ietf.org/doc/html/draft-svensson-profiled-representations-01#page-7) I believe HTTP/1.1 `300 See other` should be  `303 See other`.

**Comment by hvdsomp** [comment]
addressed in https://github.com/ProfileNegotiation/I-D-Profile-Negotiation/commit/922bb526561ac7af3ea7134d7da07ccc341bccb4
