### ISSUE TITLE
Figure 11 improvements

### ISSUE THREAD

**Issue by YoucTagh** [ProfileNegotiation/I-D-Profile-Negotiation#35]
In [Figure 11](https://datatracker.ietf.org/doc/html/draft-svensson-profiled-representations-01#page-13): 

* Why the authors use HTTP/1.1 `200 OK` rather than `300 Multiple choice`, even though reactive content negotiation is used [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.4.1-3) ? 
* Also why `Content-Length: 200` was not omitted? alternatively, `Content-Length: 458` could be use if it is the `content-length` to the same request but with a [GET](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.6-6) method.
* I think the $2^{nd}$﻿ link is missing `type =”application/xml”`.

**Comment by hvdsomp** [comment]
I see two possibilities to address this, depending on whether the server has a default representation or not:

- In case it does have a default, then `200 OK` must be used, with `Content-Lenght` of default representation, a `profile` link to indicate the profile of the default, and a single `alternate` link to point at the other representation. 
- In case it does not have a default default representation, then `300 Multiple Choices` must be used without `Content-Length`, without `profile` link, and with 2 `alternate` links.
 
Maybe both examples could be of interest.

**Comment by hvdsomp** [comment]
Addressed in https://github.com/ProfileNegotiation/I-D-Profile-Negotiation/commit/9b804b0f19121b88cf83035155549da05c1287fc and https://github.com/ProfileNegotiation/I-D-Profile-Negotiation/commit/0946a40579628afbad1cf258aae2cad3a5d70d60
