### ISSUE TITLE
Use of complies to and conforms to

### ISSUE THREAD

**Issue by YoucTagh** [ProfileNegotiation/I-D-Profile-Negotiation#39]
Is `complies to` and `conforms to` used interchangeably throughout the document?

**Comment by larsgsvensson** [comment]
Yes, I think we do. My suggestion would be to use "conforms to" everywhere.

**Comment by hvdsomp** [comment]
addressed in https://github.com/ProfileNegotiation/I-D-Profile-Negotiation/commit/922bb526561ac7af3ea7134d7da07ccc341bccb4
