### ISSUE TITLE
Minor nit in text explaining Figure 14

### ISSUE THREAD

**Issue by larsgsvensson** [ProfileNegotiation/I-D-Profile-Negotiation#45]
In [Figure 14](https://profilenegotiation.github.io/I-D-Profile-Negotiation/I-D-Profile-Negotiation.html#name-client-submits-profiled-rep) the client uses the `Content-Type` header to convey the media type. The explaining text above the figure states that the client uses the `Content-Encoding` header. That is an error.

**Comment by hvdsomp** [comment]
Addressed in https://github.com/ProfileNegotiation/I-D-Profile-Negotiation/commit/91e85e94a6872bb1fa6177b64750d9d87c15eac9
