### ISSUE TITLE
SHOULD and MUST in introduction

### ISSUE THREAD

**Issue by RubenVerborgh** [ProfileNegotiation/I-D-Profile-Negotiation#5]
There are some SHOULD and MUST statements in the introduction (before even referring to RFC2119). I wonder whether we:
- [ ] need to remove those statements from the introduction
- [ ] (also) state them in the middle section of the RDF

**Comment by larsgsvensson** [comment]
This should be resolved now. @RubenVerborgh can you please verify and close?
