### ISSUE TITLE
Update profile attribute definition to allow for multiple profile IRIs

### ISSUE THREAD

**Issue by RubenVerborgh** [ProfileNegotiation/I-D-Profile-Negotiation#8]
We should also specify the `profile` extension.

In current examples, we interestingly opted for the `profile="<http://ex.com>"` syntax. However, I think we should follow `anchor` from RFC5988 and do just `profile="http://ex.com"` to avoid the double quoting.

**Comment by RubenVerborgh** [comment]
Should also allow multiple profiles though.
- Do we keep `<>` and do comma separated for consistency with `Content-Profile`?
- Do we remove `<>` (for consistency with `anchor`, to avoid double quoting, and to have the simple common case of one URI) and do space separated?

**Comment by larsgsvensson** [comment]
> I think we should follow anchor from RFC5988 and do just profile="http://ex.com" to avoid the double quoting.

Yes, agreed. I'll fix that and also update prof-conneg accordingly. BTW the reference should be to [RFC 8288](https://tools.ietf.org/html/rfc8288).

During the work on prof-conneg, we also recognised that we need a way to associate a profile URI with a token so we need something like
```
profile="https;//example.com/profiles/123;profile1"
```
to say that a server can also use the `profile1` as an abbreviation for `https://example.com/profiles/123` _when requesting this resource_. Cf. https://github.com/w3c/dxwg/issues/290

**Comment by RubenVerborgh** [comment]
last sentence, did you mean “a client”?

Will examine token, but the semicolon won’t work (valid URL char)

**Comment by larsgsvensson** [comment]
> last sentence, did you mean “a client”?

yes...

> Will examine token, but the semicolon won’t work (valid URL char)

OK, so we'd better pick something from the reserved range.

**Comment by RubenVerborgh** [comment]
I have a felling that tokens will be hugely problematic (commented on https://github.com/w3c/dxwg/issues/290) and created a new issue to track them (https://github.com/ProfileNegotiation/I-D-Profile-Negotiation/issues/12).
