### ISSUE TITLE
Define extension points in ABNF definitions

### ISSUE THREAD

**Issue by RubenVerborgh** [ProfileNegotiation/I-D-Profile-Negotiation#9]
Should we leave extension points in our ABNF definitions, cfr. RFC5988? Will `q` as a parameter forever be enough?
Maybe we should leave open an extension point for combining multiple profiles.

**Comment by larsgsvensson** [comment]
> Should we leave extension points in our ABNF definitions, cfr. RFC5988? Will q as a parameter forever be enough?

Currently I cannot think of other parameters but of course my imagination is limited. Yes, we probably should cater for extension points. Do you think of something like

```
Accept-Profile = (# URI [accept-params])
```
where `accept-params` is defined as for the [Accept-Header in RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.3.2)?
> Maybe we should leave open an extension point for combining multiple profiles.

Do you mean that just as the current syntax
```
Accept-Profile: urn:example:1;q=0.9, urn:example:2;q=0.8
```
means `urn:example:1` __OR__ `urn:example:2` we need something that says `urn:example:1` __AND__ `urn:example:2`?

**Comment by RubenVerborgh** [comment]
Yes, probably also leave an extension point for that last case. So

```
Accept-Profile = profile-spec *("," profile-spec)
profile-spec = URI [accept-params] | profile-spec-ext
```

**Comment by larsgsvensson** [comment]
Do we need to say what we think `profile-spec-ext` would look like?

**Comment by RubenVerborgh** [comment]
I would leave it open as much as possible. Would need to not have confusion with URI `[accept-params]`, but that's hard to guarantee on an abstract syntax level.

**Comment by larsgsvensson** [comment]
> I would leave it open as much as possible.

OK. Then I guess we'd define `Content-Profile` similarly:
```
Content-Profile = profile-spec *("," profile-spec )
```
Then, however, we'd have `accept-params` in `Content-profile` which feels a bit awkward, so perhaps it's better with
```
Content-Profile = URI *("," URI ) | content-profile-spec-ext
```
where we say as little as possible about what `content-profile-spec-ext` means.
